---
  project_name: anchorctl
  
  release:
    github:
      owner: covarity
      name: anchorctl
  
  builds:
    - main : ./cmd/main.go
      binary: anchorctl
      goos:
        - darwin
        - linux
        - windows
      goarch:
        - amd64
      ldflags: -X anchorctl/pkg/cmd.Version={{.Version}} -X main.GitTag={{.Tag}} -X anchorctl/pkg/cmd.Build={{.Date}}
      env:
        - GO111MODULE=on
  archive:
    files:
      - README.md
      - LICENSE