sudo: false

matrix:
  include:
    - language: go
      name: linters go
      go: 1.13.x
      before_script:
        - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -x -- -b $(go env GOPATH)/bin v1.18.0
      script:
        - golangci-lint run
    - language: go
      name: tests and coverage go
      go: 1.13.x
      script:
        - go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
        - bash <(curl -s https://codecov.io/bash) -cF go
