apiVersion: anchor.covarity.dev/alpha1v1
kind: KubeTest
metadata:
  name: opa-validation
spec:
  lifecycle:
    postStart:
    - path: "./fixtures/applications-ns.yaml"
      action: "CREATE"
    - path: "./fixtures/hello-world-nginx.yaml"
      action: "CREATE"
    preStop:
      - path: "./fixtures/hello-world-nginx.yaml"
        action: "DELETE"
      - path: "./fixtures/applications-ns.yaml"
        action: "DELETE"
  tests:
  - type: AssertJSONPath
    spec:
      jsonPath: ".spec.containers[0].image"
      value: "nginx"
    resource:
      objectRef:
        type: Resource
        spec:
          kind: Pod
          namespace: applications
          labelKey: hello
          labelValue: world
  - type: AssertValidation
    spec:
      expectedError: "Internal error occurred: admission webhook \"webhook.openpolicyagent.org\" denied the request: External Loadbalancers cannot be deployed in this cluster"
    resource:
      manifest:
        path: "./fixtures/loadbalancer.yaml"
        action: CREATE
  - type: AssertMutation
    spec:
      jsonPath: ".metadata.labels.function"
      value: "workload"
    resource:
      manifest:
        path: "./fixtures/deploy.yaml"
        action: CREATE
