apiVersion: anchor.covarity.dev/alpha1v1
kind: KubeTest
metadata:
  name: opa-validation
spec:
  lifecycle:
    postStart:
    - path: "./fixtures/applications-ns.yaml"
      action: "CREATE"
    - path: "./fixtures/hello-world-nginx.yaml"
      action: "CREATE"
    preStop:
      - path: "./fixtures/hello-world-nginx.yaml"
        action: "DELETE"
      - path: "./fixtures/applications-ns.yaml"
        action: "DELETE"
  tests:
  - type: AssertJSONPath
    spec:
      jsonPath: ".spec.containers[0].image"
      value: "nginx"
    resource:
      objectRef:
        type: Resource
        spec:
          kind: Pod
          namespace: applications
          labels:
            hello: world
  - type: AssertValidation
    spec:
      containsResponse: "External Loadbalancers cannot be deployed in this cluster"
    resource:
      manifest:
        path: "./fixtures/loadbalancer.yaml"
        action: CREATE
  - type: AssertMutation
    spec:
      jsonPath: ".metadata.labels.billing-information"
      value: "ACC108964"
    resource:
      manifest:
        path: "./fixtures/deploy.yaml"
        action: CREATE
  - type: AssertMutation
    spec:
      jsonPath: ".metadata.labels.billing-information"
      value: "DEMO-BILLING"
    resource:
      manifest:
        path: "./fixtures/demo-deploy.yaml"
        action: CREATE