apiVersion: anchor.covarity.dev/alpha1v1
kind: KubeTest
metadata:
  name: opa-validation
spec:
  tests:
  - type: AssertJSONPath
    spec:
      jsonPath: ".spec.nodeName"
      value: "docker-desktop"
    objectRef:
      type: Pod
      spec:
        namespace: default
        labelKey: run
        labelValue: nginx
  - type: AssertValidation
    spec:
      expectedError: "Internal error occurred: admission webhook \"webhook.openpolicyagent.org\" denied the request: External Loadbalancers cannot be deployed in this cluster"
    objectRef:
      type: File
      spec:
        path: "./samples/fixtures/loadbalancer.yaml"
        action: CREATE
  - type: AssertMutation
    spec:
      jsonPath: ".metadata.labels.function"
      value: "workload"
    objectRef:
      type: File
      spec:
        path: "./samples/fixtures/deploy.yaml"
        action: CREATE
