name: E2ETest
on: [pull_request, push]
jobs:
  integration-tests:
    name: create-kind-cluster 
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: install-kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: build-image
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --skip-publish
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide
